import fs from 'fs-extra';
import path from 'path';
import { ScannerResult } from '../analyzer/repoScanner';

export async function generateArchitecture(rootDir: string, scannerResult: ScannerResult): Promise<void> {
  const archPath = path.join(rootDir, '.ai', 'architecture.md');
  const content = `# Architecture

## System Overview
Generated by ai-workspace.

## Detected Entrypoints
${scannerResult.entrypoints.map(e => `- \`${e}\``).join('\n')}

## Components Layer
Review the \`repo-map.json\` to understand the complete directory structure.
`;

  await fs.writeFile(archPath, content);
}
