import { Command } from 'commander';
import fs from 'fs-extra';
import path from 'path';

export const exportCommand = new Command('export')
  .description('Export .ai rules to tool-specific manifests (e.g., .cursorrules)')
  .option('-t, --target <target>', 'Target tool (cursor, windsurf, all)', 'cursor')
  .action(async (options) => {
    try {
      const cwd = process.cwd();
      const aiDir = path.join(cwd, '.ai');
      const rulesPath = path.join(aiDir, 'rules.md');

      if (!fs.existsSync(rulesPath)) {
        console.error('Error: .ai/rules.md not found. Run "ai-workspace generate" first.');
        process.exit(1);
      }

      console.log(`Reading rules from ${rulesPath}...`);
      const rulesContent = await fs.readFile(rulesPath, 'utf8');

      const header = `\n# --- EXPORTED FROM AI-WORKSPACE ---\n# AI-Workspace converts this repo into an AI-ready context.\n# DO NOT EDIT THIS FILE DIRECTLY. Edit .ai/rules.md instead.\n\n`;
      const finalContent = header + rulesContent;

      const targets: string[] = [];
      if (options.target === 'all') {
        targets.push('.cursorrules', '.windsurfrules');
      } else if (options.target === 'cursor') {
        targets.push('.cursorrules');
      } else if (options.target === 'windsurf') {
        targets.push('.windsurfrules');
      }

      for (const targetFile of targets) {
        const targetPath = path.join(cwd, targetFile);
        await fs.writeFile(targetPath, finalContent);
        console.log(`Successfully exported rules to ${targetFile} ✔`);
      }

    } catch (error) {
      console.error('Error during export:', error);
      process.exit(1);
    }
  });
