import { Command } from 'commander';
import fs from 'fs-extra';
import path from 'path';
import { isAgentEnvironment } from '../utils/agentDetector';
import { scanRepository } from '../analyzer/repoScanner';
import { generateRepoMap } from '../generators/repoMapGenerator';
import { generateRepoContext } from '../generators/repoContextGenerator';

export const initCommand = new Command('init')
  .description('Initialize AI workspace by creating the .ai directory and base structure')
  .action(async () => {
    try {
      const cwd = process.cwd();
      const aiDir = path.join(cwd, '.ai');
      const rootDir = cwd; 

      console.log('Initializing ai-workspace...');

      await fs.ensureDir(aiDir);
      await fs.ensureDir(path.join(aiDir, 'context'));
      await fs.ensureDir(path.join(aiDir, 'decisions'));
      await fs.ensureDir(path.join(aiDir, 'skills'));

      // Config
      const configPath = path.join(aiDir, 'config.json');
      if (!fs.existsSync(configPath)) {
        await fs.writeJSON(configPath, {
          provider: "openai",
          model: "gpt-4",
          openaiKey: "PASTE_YOUR_OPENAI_KEY_HERE",
          anthropicKey: "PASTE_YOUR_ANTHROPIC_KEY_HERE"
        }, { spaces: 2 });
      }

      // Skills index
      const skillsIndexPath = path.join(aiDir, 'skills', 'index.json');
      if (!fs.existsSync(skillsIndexPath)) {
        await fs.writeJSON(skillsIndexPath, { skills: [] }, { spaces: 2 });
      }

      // Markdown Placeholders
      const files = [
        { path: 'project.md', content: '# Project Summary\\n\\nGenerated by LLM.\\n' },
        { path: 'architecture.md', content: '# Architecture\\n\\nGenerated by LLM.\\n' },
        { path: 'rules.md', content: '# Rules\\n\\nDefine global rules here.\\n' },
        { path: 'decisions/initial-decisions.md', content: '# Initial Decisions\\n\\nGenerated by LLM.\\n' }
      ];

      for (const file of files) {
        const fullPath = path.join(aiDir, file.path);
        if (!fs.existsSync(fullPath)) {
          await fs.writeFile(fullPath, file.content);
        }
      }

      console.log('ai-workspace successfully initialized in .ai/');

      // If an agent is driving us, automatically generate the context and output a prompt
      if (isAgentEnvironment()) {
        console.log('\\n[Agent Detected] Running automatic analysis...\\n');
        
        try {
          const scannerResult = await scanRepository(rootDir);
          await generateRepoMap(rootDir, scannerResult);
          await generateRepoContext(rootDir, scannerResult);
          
          console.log('--- AI AGENT INSTRUCTIONS ---');
          console.log('I am the ai-workspace CLI. I have detected you are an AI agent.');
          console.log('I have just generated extreme context mapping inside:');
          console.log('  .ai/repo-map.json');
          console.log('  .ai/context/repo-context.json');
          console.log('');
          console.log('Your immediate task is to read those context files and write high-quality,');
          console.log('highly-detailed, project-specific documentation and domain rules into:');
          console.log('  1. .ai/project.md');
          console.log('  2. .ai/architecture.md');
          console.log('  3. .ai/rules.md');
          console.log('');
          console.log('Use your own advanced reasoning to figure out the best rules and architecture patterns.');
          console.log('Do not leave them empty!');
          console.log('-----------------------------');
        } catch (e) {
          console.warn('Agent auto-analysis failed. Please run "ai-workspace analyze" manually.', e);
        }
      }

    } catch (error) {
      console.error('Error initializing ai-workspace:', error);
      process.exit(1);
    }
  });
