import { Command } from 'commander';
import fs from 'fs-extra';
import path from 'path';

export const initCommand = new Command('init')
  .description('Initialize AI workspace by creating the .ai directory and base structure')
  .action(async () => {
    const cwd = process.cwd();
    const aiDir = path.join(cwd, '.ai');

    console.log('Initializing ai-workspace...');

    await fs.ensureDir(aiDir);
    await fs.ensureDir(path.join(aiDir, 'context'));
    await fs.ensureDir(path.join(aiDir, 'decisions'));
    await fs.ensureDir(path.join(aiDir, 'skills'));

    // Config
    const configPath = path.join(aiDir, 'config.json');
    if (!fs.existsSync(configPath)) {
      await fs.writeJSON(configPath, {
        provider: "openai",
        model: "gpt-4"
      }, { spaces: 2 });
    }

    // Skills index
    const skillsIndexPath = path.join(aiDir, 'skills', 'index.json');
    if (!fs.existsSync(skillsIndexPath)) {
      await fs.writeJSON(skillsIndexPath, { skills: [] }, { spaces: 2 });
    }

    // Markdown Placeholders
    const files = [
      { path: 'project.md', content: '# Project Summary\n\nGenerated by LLM.\n' },
      { path: 'architecture.md', content: '# Architecture\n\nGenerated by LLM.\n' },
      { path: 'rules.md', content: '# Rules\n\nDefine global rules here.\n' },
      { path: 'decisions/initial-decisions.md', content: '# Initial Decisions\n\nGenerated by LLM.\n' }
    ];

    for (const file of files) {
      const fullPath = path.join(aiDir, file.path);
      if (!fs.existsSync(fullPath)) {
        await fs.writeFile(fullPath, file.content);
      }
    }

    console.log('ai-workspace successfully initialized in .ai/');
  });
